/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as AuthedRouteImport } from './routes/_authed.tsx'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up.tsx'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in.tsx'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard.tsx'
import { Route as AuthedAnalyzeRepoIdRouteImport } from './routes/_authed/analyze/$repoId.tsx'
import { Route as AuthedReposRepoIdAnalysesIndexRouteImport } from './routes/_authed/repos/$repoId/analyses/index'
import { Route as AuthedReposRepoIdAnalysesAnalysisIdRouteImport } from './routes/_authed/repos/$repoId/analyses/$analysisId.tsx'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalyzeRepoIdRoute = AuthedAnalyzeRepoIdRouteImport.update({
  id: '/analyze/$repoId',
  path: '/analyze/$repoId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReposRepoIdAnalysesIndexRoute =
  AuthedReposRepoIdAnalysesIndexRouteImport.update({
    id: '/repos/$repoId/analyses/',
    path: '/repos/$repoId/analyses/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedReposRepoIdAnalysesAnalysisIdRoute =
  AuthedReposRepoIdAnalysesAnalysisIdRouteImport.update({
    id: '/repos/$repoId/analyses/$analysisId',
    path: '/repos/$repoId/analyses/$analysisId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/analyze/$repoId': typeof AuthedAnalyzeRepoIdRoute
  '/repos/$repoId/analyses/$analysisId': typeof AuthedReposRepoIdAnalysesAnalysisIdRoute
  '/repos/$repoId/analyses/': typeof AuthedReposRepoIdAnalysesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/analyze/$repoId': typeof AuthedAnalyzeRepoIdRoute
  '/repos/$repoId/analyses/$analysisId': typeof AuthedReposRepoIdAnalysesAnalysisIdRoute
  '/repos/$repoId/analyses': typeof AuthedReposRepoIdAnalysesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_authed/analyze/$repoId': typeof AuthedAnalyzeRepoIdRoute
  '/_authed/repos/$repoId/analyses/$analysisId': typeof AuthedReposRepoIdAnalysesAnalysisIdRoute
  '/_authed/repos/$repoId/analyses/': typeof AuthedReposRepoIdAnalysesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/analyze/$repoId'
    | '/repos/$repoId/analyses/$analysisId'
    | '/repos/$repoId/analyses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/analyze/$repoId'
    | '/repos/$repoId/analyses/$analysisId'
    | '/repos/$repoId/analyses'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_authed/analyze/$repoId'
    | '/_authed/repos/$repoId/analyses/$analysisId'
    | '/_authed/repos/$repoId/analyses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analyze/$repoId': {
      id: '/_authed/analyze/$repoId'
      path: '/analyze/$repoId'
      fullPath: '/analyze/$repoId'
      preLoaderRoute: typeof AuthedAnalyzeRepoIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/repos/$repoId/analyses/': {
      id: '/_authed/repos/$repoId/analyses/'
      path: '/repos/$repoId/analyses'
      fullPath: '/repos/$repoId/analyses/'
      preLoaderRoute: typeof AuthedReposRepoIdAnalysesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/repos/$repoId/analyses/$analysisId': {
      id: '/_authed/repos/$repoId/analyses/$analysisId'
      path: '/repos/$repoId/analyses/$analysisId'
      fullPath: '/repos/$repoId/analyses/$analysisId'
      preLoaderRoute: typeof AuthedReposRepoIdAnalysesAnalysisIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedAnalyzeRepoIdRoute: typeof AuthedAnalyzeRepoIdRoute
  AuthedReposRepoIdAnalysesAnalysisIdRoute: typeof AuthedReposRepoIdAnalysesAnalysisIdRoute
  AuthedReposRepoIdAnalysesIndexRoute: typeof AuthedReposRepoIdAnalysesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedAnalyzeRepoIdRoute: AuthedAnalyzeRepoIdRoute,
  AuthedReposRepoIdAnalysesAnalysisIdRoute:
    AuthedReposRepoIdAnalysesAnalysisIdRoute,
  AuthedReposRepoIdAnalysesIndexRoute: AuthedReposRepoIdAnalysesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
